"""Константы приложения cask."""

MAX_LENGTH_BARREL_MANUFACTURER = 30
MAX_LENGTH_TYPE_OF_OAK = 30
MAX_NAME_CASK = 30
MIN_VALUE_FILLING_BARREL = 1
MAX_VALUE_FILLING_BARREL = 7
MIN_VOLUME_VALUE = 3
MAX_VOLUME_VALUE = 1000
